# distrochooser
# Copyright (C) 2014-2025 Christoph Müller  <mail@chmr.eu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# distrochooser::translation::eng::I want to install my programs using a kind of "App store"
# distrochooser::translation::key::app-store-gui-description
[facette.app-store-gui]
topic = "administration"

# distrochooser::translation::eng::I want to install software mostly using terminal commands
# distrochooser::translation::key::software-admin-answer-console-description
[facette.software-admin-answer-console]
topic = "administration"

# distrochooser::translation::eng::I want to avoid systemd
# distrochooser::translation::key::no-systemd-description
[facette.no-systemd]
topic = "administration"

