# distrochooser
# Copyright (C) 2014-2025 Christoph Müller  <mail@chmr.eu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# distrochooser::translation::eng::I prefer a free-to-use distribution
# distrochooser::translation::key::pricing-free-description
[facette.pricing-free]
topic = "pricing"

# distrochooser::translation::eng::I would be fine to pay a fee
# distrochooser::translation::key::paid-support-ok-description
[facette.paid-support-ok]
topic = "pricing"