name: Bug report
description: Create a report to help us improve
title: '[Bug]: '
labels: ["bug"]
assignees: "cmllr"
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the bug as detailed as possible. Please also mention the expected behaviour!
      placeholder: Tell us what you see!
      value: "A bug happened!"
  - type: dropdown
    id: mobile
    attributes:
      label: Mobile device
      description: Is the device a mobile device?
      options:
        - "Yes"
        - "No"
      default: 1
    
  - type: dropdown
    id: instance
    attributes:
      label: What page were you using?
      description: Please add the URL to the page
      multiple: false
      default: 0
      options:
        - distrochooser.de
        - beta.distrochooser.de
    validations:
      required: false