name: Feature request
description: Request feature you would like to see in the project. Also use this to suggest distributions.
title: '[Feature-Request]: '
labels: ['feature request', 'request']
assignees: "cmllr"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: request
    attributes:
      label: Describe your feature
      description: Please be as specific as possible
      placeholder: Tell us what you see!
      value: "My feature request"
  - type: dropdown
    id: components
    attributes:
      label: Components
      description: What components does this feature affect?
      multiple: true
      options:
        - "Frontend"
        - "Backend"
        - "Decision finding"
        - "Distribution addition"
      default: 1