# kuusi
# Copyright (C) 2014-2024  Christoph Müller  <mail@chmr.eu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[[choosable]]
catalogue_id="ubuntu"
bg_color="#E95420"
fg_color="#FFFFFF"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://ubuntu.com"
[[choosable]]
catalogue_id="debian"
bg_color="#d70a53"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://debian.org"
[[choosable]]
catalogue_id="tails"
bg_color="#56347c"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://tails.boum.org/"
[[choosable]]
catalogue_id="devuan"
bg_color="#E5EDB0"
fg_color="#662984"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://devuan.org/"
[[choosable]]
catalogue_id="arch"
bg_color="#08c"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://www.archlinux.org/"
[[choosable]]
catalogue_id="mint"
bg_color="#a4e265"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://www.linuxmint.com/"
[[choosable]]
catalogue_id="opensuse"
bg_color="#173f4f"
fg_color="#35b9ab"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://www.opensuse.org/"
[[choosable]]
catalogue_id="solus"
bg_color="#5294E2"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://getsol.us/home/"
[[choosable]]
catalogue_id="manjaro"
bg_color="#34be5b"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://manjaro.org"
[[choosable]]
catalogue_id="pclinuxos"
bg_color="black"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="http://www.pclinuxos.com/"
[[choosable]]
catalogue_id="rocky"
bg_color="#10b981"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://rockylinux.org/"
[[choosable]]
catalogue_id="rhel"
bg_color="#cf0000"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://www.redhat.com/de/technologies/linux-platforms/enterprise-linux"
[[choosable]]
catalogue_id="mxlinux"
bg_color="#134452"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://mxlinux.org/"
[[choosable]]
catalogue_id="fedora"
bg_color="#3c6eb4"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://getfedora.org/"
[[choosable]]
catalogue_id="gentoo"
bg_color="#4d4270"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://www.gentoo.org/"
[[choosable]]
catalogue_id="knoppix"
bg_color="#dddddd"
fg_color="blue"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="http://www.knoppix.org/"
[[choosable]]
catalogue_id="cruxlinux"
bg_color="#dfeeee"
fg_color="black"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://crux.nu/"
[[choosable]]
catalogue_id="zorinos"
bg_color="#15a6f0"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://zorin.com/os/"
[[choosable]]
catalogue_id="elementaryos"
bg_color="#555761"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://elementary.io/"
[[choosable]]
catalogue_id="qubesos"
bg_color="#f5f5f5"
fg_color="black"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://www.qubes-os.org/"
[[choosable]]
catalogue_id="nixos"
bg_color="None"
fg_color="None"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="None"
[[choosable]]
catalogue_id="xubuntu"
bg_color="#0c72b7"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://xubuntu.org/"
[[choosable]]
catalogue_id="lubuntu"
bg_color="#3e2e53"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://lubuntu.me/"
[[choosable]]
catalogue_id="ubuntumate"
bg_color="#87a556"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://ubuntu-mate.org/"
[[choosable]]
catalogue_id="void"
bg_color="#478061"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://voidlinux.org/"
[[choosable]]
catalogue_id="artix"
bg_color="black"
fg_color="#8bf"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://artixlinux.org/"
[[choosable]]
catalogue_id="kubuntu"
bg_color="#0079C1"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://kubuntu.org/"
[[choosable]]
catalogue_id="popos"
bg_color="#48b9c7"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://pop.system76.com/"
[[choosable]]
catalogue_id="deepin"
bg_color="#2fc6ff"
fg_color="white"
[[choosable.meta]]
meta_type="link"
meta_name="website"
meta_value="https://www.deepin.org/en/"
