# kuusi
# Copyright (C) 2014-2024  Christoph Müller  <mail@chmr.eu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[[choosable]]
catalogue_id = "debian"
[[choosable.meta]]
meta_type = "link"
meta_name = "website"
meta_value = "https://www.debian.org/"
[[choosable.meta]]
meta_type = "text"
meta_name = "licenses"
meta_value = "DFSG"
[[choosable.meta]]
meta_type = "date"
meta_name = "created"
meta_value = "https://www.debian.org/"
[[choosable.meta]]
meta_type = "date"
meta_name = "created"
meta_value = "1993-08-16"
[[choosable.meta]]
meta_type = "flag"
meta_name = "country"
meta_value = "us"
