name: Annotation

on:
  issue_comment:
    types: [created]



jobs:
  annotate:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/check')
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "${{ github.action_ref }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r code/kuusi/requirements.txt
      - run: cd code/kuusi/ && python manage.py makemigrations
      - run: cd code/kuusi/ &&python manage.py migrate
      - run: cd code/kuusi/ &&python manage.py parse ../../matrix/matrix.toml
      - run: cd code/kuusi/ &&python manage.py annotate ../../matrix/ > ./annotation.txt
      - name: Add workflow result as comment on PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const name = '${{ github.workflow	}}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const fs = require('fs')
            const annotationText = fs.readFileSync('./code/kuusi/annotation.txt')
            console.log(annotationText)
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `annotationText`
            })

