# distrochooser
# Copyright (C) 2014-2025 Christoph Müller  <mail@chmr.eu>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


[assignment.supports-daily-usage-facette-daily-usage]
facettes = ["daily-usage"]
choosables = [
    "ubuntu",
    "debian",
    "devuan",
    "arch",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "rocky",
    "rhel",
    "MXLinux",
    "Fedora",
    "Gentoo",
    "CruxLinux",
    "ZorinOS",
    "elementaryOS",
    "qubesos",
    "nixOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "void",
    "artix",
    "kubuntu",
    "popos",
    "deepin",
]
how = "positive"


[assignment.daily-usage-possibly-difficult-facette-daily-usage]
facettes = ["daily-usage"]
choosables = ["tails"]
how = "negative"


[assignment.supports-daily-usage-but-built-for-livemode-facette-daily-usage]
facettes = ["daily-usage"]
choosables = ["Knoppix"]
how = "negative"


[assignment.privacy-not-beneficial-facette-privacy-usage]
facettes = ["privacy-usage"]
choosables = ["ubuntu", "deepin"]
how = "blocking"


[assignment.packages-available-facette-privacy-usage]
facettes = ["privacy-usage"]
choosables = [
    "debian",
    "devuan",
    "arch",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "rocky",
    "rhel",
    "MXLinux",
    "Fedora",
    "Gentoo",
    "Knoppix",
    "CruxLinux",
    "ZorinOS",
    "elementaryOS",
    "qubesos",
    "nixOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "void",
    "artix",
    "popos",
]
how = "neutral"


[assignment.built-for-anonymization-facette-privacy-usage]
facettes = ["privacy-usage"]
choosables = ["tails"]
how = "positive"


[assignment.supports-gaming-usage-facette-gaming-usage]
facettes = ["gaming-usage"]
choosables = [
    "ubuntu",
    "mint",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
    "deepin",
]
how = "positive"


[assignment.packages-may-too-old-gaming-facette-gaming-usage]
facettes = ["gaming-usage"]
choosables = ["debian", "devuan", "rocky", "MXLinux"]
how = "negative"


[assignment.live-mode-only-facette-gaming-usage]
facettes = ["gaming-usage"]
choosables = ["tails"]
how = "blocking"


[assignment.gaming-may-require-additional-configuration-facette-gaming-usage]
facettes = ["gaming-usage"]
choosables = [
    "arch",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "Fedora",
    "Gentoo",
    "void",
    "artix",
]
how = "neutral"


[assignment.built-for-enterprise-facette-gaming-usage]
facettes = ["gaming-usage"]
choosables = ["rhel"]
how = "negative"


[assignment.not-built-for-gaming-facette-gaming-usage]
facettes = ["gaming-usage"]
choosables = ["Knoppix", "CruxLinux", "qubesos"]
how = "negative"


[assignment.beginner-knowledge-facette-beginner-usage]
facettes = ["beginner-usage"]
choosables = [
    "ubuntu",
    "mint",
    "opensuse",
    "solus",
    "pclinuxos",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
    "deepin",
]
how = "positive"


[assignment.requires-some-computer-knowledge-facette-beginner-usage]
facettes = ["beginner-usage"]
choosables = [
    "debian",
    "tails",
    "devuan",
    "arch",
    "manjaro",
    "rocky",
    "rhel",
    "MXLinux",
    "Fedora",
    "Gentoo",
    "Knoppix",
    "CruxLinux",
    "qubesos",
    "nixOS",
    "void",
    "artix",
]
how = "negative"


[assignment.requires-advanced-knowledge-facette-advanced-usage]
facettes = ["advanced-usage"]
choosables = [
    "debian",
    "devuan",
    "arch",
    "manjaro",
    "rocky",
    "rhel",
    "MXLinux",
    "Fedora",
    "Gentoo",
    "Knoppix",
    "CruxLinux",
    "qubesos",
    "void",
    "artix",
]
how = "positive"


[assignment.requires-advanced-knowledge-facette-professional-usage]
facettes = ["professional-usage"]
choosables = [
    "debian",
    "devuan",
    "arch",
    "opensuse",
    "rocky",
    "rhel",
    "Gentoo",
    "qubesos",
    "nixOS",
    "void",
    "artix",
]
how = "positive"


[assignment.beginner-knowledge-facette-no-linux-contact]
facettes = ["no-linux-contact"]
choosables = [
    "ubuntu",
    "mint",
    "opensuse",
    "solus",
    "pclinuxos",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
    "deepin",
]
how = "positive"


[assignment.not-for-beginner-facette-no-linux-contact]
facettes = ["no-linux-contact"]
choosables = [
    "debian",
    "devuan",
    "arch",
    "manjaro",
    "rocky",
    "rhel",
    "MXLinux",
    "Gentoo",
    "Knoppix",
    "qubesos",
    "nixOS",
    "void",
    "artix",
]
how = "blocking"


[assignment.maybe-not-for-beginner-facette-no-linux-contact]
facettes = ["no-linux-contact"]
choosables = ["MXLinux", "Fedora", "Knoppix", "CruxLinux", "qubesos", "nixOS"]
how = "negative"


[assignment.requires-manual-facette-already-used]
facettes = ["already-used"]
choosables = [
    "debian",
    "devuan",
    "arch",
    "opensuse",
    "manjaro",
    "rocky",
    "rhel",
    "MXLinux",
    "Gentoo",
    "Knoppix",
    "CruxLinux",
    "qubesos",
    "nixOS",
    "void",
    "artix",
]
how = "positive"


[assignment.installation-assistant-present-facette-many-preselections]
facettes = ["many-preselections"]
choosables = [
    "ubuntu",
    "debian",
    "devuan",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "rocky",
    "rhel",
    "MXLinux",
    "Fedora",
    "Knoppix",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
    "deepin",
]
how = "positive"


[assignment.has-default-settings-facette-many-preselections]
facettes = ["many-preselections"]
choosables = [
    "ubuntu",
    "mint",
    "opensuse",
    "solus",
    "Fedora",
    "Knoppix",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
    "deepin",
]
how = "positive"


[assignment.installation-facettes-shell-facette-many-preselections]
facettes = ["many-preselections"]
choosables = ["arch", "Gentoo", "void", "artix"]
how = "blocking"


[assignment.installs-range-of-programs-facette-commandline-setup]
facettes = ["commandline-setup"]
choosables = [
    "ubuntu",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "MXLinux",
    "Fedora",
    "Knoppix",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
    "deepin",
]
how = "negative"


[assignment.selection-by-user-facette-commandline-setup]
facettes = ["commandline-setup"]
choosables = [
    "debian",
    "devuan",
    "arch",
    "opensuse",
    "rocky",
    "rhel",
    "Gentoo",
    "CruxLinux",
    "void",
    "artix",
]
how = "positive"


[assignment.installation-presets-gui-facette-many-choices-gui]
facettes = ["many-choices-gui"]
choosables = [
    "ubuntu",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "Fedora",
    "Knoppix",
    "ZorinOS",
    "elementaryOS",
    "nixOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "deepin",
]
how = "positive"


[assignment.has-control-panel-facette-many-choices-gui]
facettes = ["many-choices-gui"]
choosables = [
    "ubuntu",
    "mint",
    "opensuse",
    "solus",
    "pclinuxos",
    "Fedora",
    "Knoppix",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
    "deepin",
]
how = "positive"


[assignment.configuration-facettes-shell-facette-many-choices-gui]
facettes = ["many-choices-gui"]
choosables = ["arch", "Gentoo"]
how = "blocking"


[assignment.oldpc-no-32bit-facette-no64bit]
facettes = ["no64bit"]
choosables = [
    "ubuntu",
    "arch",
    "pclinuxos",
    "Fedora",
    "CruxLinux",
    "ZorinOS",
    "Lubuntu",
    "artix",
    "popos",
    "deepin",
]
how = "blocking"


[assignment.middleweight-facette-no64bit]
facettes = ["no64bit"]
choosables = ["MXLinux"]
how = "positive"


[assignment.has-high-range-hardware-support-facette-no64bit]
facettes = ["no64bit"]
choosables = ["Knoppix"]
how = "positive"


[assignment.has-zorin-lite-version-facette-no64bit]
facettes = ["no64bit"]
choosables = ["ZorinOS"]
how = "positive"


[assignment.no64bit-support]
facettes = ["no64bit"]
choosables = [
    "ubuntu",
    "tails",
    "devuan",
    "arch",
    "mint",
    "solus",
    "manjaro",
    "pclinuxos",
    "rocky",
    "rhel",
    "Fedora",
    "CruxLinux",
    "ZorinOS",
    "elementaryOS",
    "qubesos",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "artix",
    "kubuntu",
    "popos",
    "deepin",
]
how = "negative"


[assignment.lightweight-facette-no64bit]
facettes = ["no64bit"]
choosables = ["elementaryOS", "Xubuntu", "Lubuntu", "UbuntuMATE"]
how = "positive"


[assignment.tutorial-facette-manuals]
facettes = ["manuals"]
choosables = [
    "debian",
    "tails",
    "devuan",
    "arch",
    "opensuse",
    "rocky",
    "rhel",
    "MXLinux",
    "Fedora",
    "Gentoo",
    "Knoppix",
    "CruxLinux",
    "qubesos",
    "nixOS",
    "void",
    "artix",
]
how = "positive"


[assignment.user-exchange-facette-need-human-help]
facettes = ["need-human-help"]
choosables = [
    "ubuntu",
    "mint",
    "solus",
    "manjaro",
    "pclinuxos",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
]
how = "positive"


[assignment.has-windows-like-variant-cinnamon-facette-ux-concept-answer-windows-like]
facettes = ["ux-concept-answer-windows-like"]
choosables = ["mint"]
how = "positive"


[assignment.has-windows-like-variant-facette-ux-concept-answer-windows-like]
facettes = ["ux-concept-answer-windows-like"]
choosables = ["pclinuxos", "Knoppix", "ZorinOS", "Lubuntu", "kubuntu"]
how = "positive"


[assignment.mac-like-facette-ux-concept-answer-mac-like]
facettes = ["ux-concept-answer-mac-like"]
choosables = ["popos", "deepin"]
how = "positive"


[assignment.without-fee-facette-pricing-free]
facettes = ["pricing-free"]
choosables = [
    "ubuntu",
    "debian",
    "tails",
    "devuan",
    "arch",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "rocky",
    "MXLinux",
    "Fedora",
    "Gentoo",
    "Knoppix",
    "CruxLinux",
    "ZorinOS",
    "elementaryOS",
    "qubesos",
    "nixOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "void",
    "artix",
    "kubuntu",
    "popos",
    "deepin",
]
how = "positive"


[assignment.paid-version-existing-facette-paid-support-ok]
facettes = ["paid-support-ok"]
choosables = ["ubuntu", "opensuse", "rhel", "ZorinOS", "elementaryOS"]
how = "positive"


[assignment.fullinstall-facette-scope-out-of-the-box]
facettes = ["scope-out-of-the-box"]
choosables = [
    "ubuntu",
    "devuan",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "rocky",
    "rhel",
    "MXLinux",
    "Fedora",
    "Knoppix",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
    "deepin",
]
how = "positive"


[assignment.free-software-unfree-per-default-facette-license-open-source]
facettes = ["license-open-source"]
choosables = [
    "ubuntu",
    "mint",
    "manjaro",
    "pclinuxos",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "popos",
]
how = "blocking"


[assignment.free-userselection-facette-license-open-source]
facettes = ["license-open-source"]
choosables = ["debian", "devuan", "arch", "rocky", "Gentoo", "artix"]
how = "positive"


[assignment.enforces-free-facette-license-open-source]
facettes = ["license-open-source"]
choosables = ["Fedora"]
how = "positive"


[assignment.free-software-unfree-per-default-facette-proprietary-okay-when-working]
facettes = ["proprietary-okay-when-working"]
choosables = [
    "ubuntu",
    "mint",
    "manjaro",
    "pclinuxos",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
    "deepin",
]
how = "positive"


[assignment.privacy-thirdparty-facette-privacy-no-connections-unless-wanted]
facettes = ["privacy-no-connections-unless-wanted"]
choosables = []
how = "blocking"


[assignment.user-selection-affects-privacy-facette-privacy-no-connections-unless-wanted]
facettes = ["privacy-no-connections-unless-wanted"]
choosables = [
    "debian",
    "tails",
    "devuan",
    "arch",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "rocky",
    "rhel",
    "MXLinux",
    "Fedora",
    "Gentoo",
    "Knoppix",
    "CruxLinux",
    "ZorinOS",
    "qubesos",
    "void",
    "artix",
]
how = "positive"


[assignment.supports-privacy-facette-privacy-no-connections-unless-wanted]
facettes = ["privacy-no-connections-unless-wanted"]
choosables = ["elementaryOS"]
how = "positive"


[assignment.privacy-thirdparty-facette-okay-when-working]
facettes = ["okay-when-working"]
choosables = ["ubuntu"]
how = "negative"


[assignment.appstore-facette-app-store-gui]
facettes = ["app-store-gui"]
choosables = [
    "ubuntu",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
]
how = "positive"


[assignment.console-facette-software-admin-answer-console]
facettes = ["software-admin-answer-console"]
choosables = [
    "ubuntu",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
]
how = "neutral"


[assignment.administration-shell-facette-software-admin-answer-console]
facettes = ["software-admin-answer-console"]
choosables = [
    "debian",
    "tails",
    "devuan",
    "arch",
    "rocky",
    "rhel",
    "MXLinux",
    "Fedora",
    "Gentoo",
    "Knoppix",
    "CruxLinux",
    "qubesos",
    "nixOS",
    "void",
    "artix",
]
how = "positive"


[assignment.uses-systemd-facette-no-systemd]
facettes = ["no-systemd"]
choosables = [
    "ubuntu",
    "debian",
    "tails",
    "arch",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "rocky",
    "rhel",
    "Fedora",
    "ZorinOS",
    "elementaryOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
    "deepin",
]
how = "blocking"


[assignment.avoids-systemd-facette-no-systemd]
facettes = ["no-systemd"]
choosables = ["devuan", "pclinuxos", "Knoppix", "CruxLinux", "artix"]
how = "positive"


[assignment.systemd-is-avoidable-per-selection-facette-no-systemd]
facettes = ["no-systemd"]
choosables = ["Gentoo", "void"]
how = "positive"


[assignment.ships-systemd-but-disabled-facette-no-systemd]
facettes = ["no-systemd"]
choosables = ["MXLinux"]
how = "positive"


[assignment.updates-fast-facette-prefer-fast]
facettes = ["prefer-fast"]
choosables = [
    "arch",
    "solus",
    "manjaro",
    "pclinuxos",
    "Fedora",
    "Gentoo",
    "CruxLinux",
    "void",
    "artix",
]
how = "positive"


[assignment.stable-updates-facette-prefer-stable]
facettes = ["prefer-stable"]
choosables = [
    "ubuntu",
    "debian",
    "tails",
    "devuan",
    "mint",
    "opensuse",
    "rocky",
    "rhel",
    "MXLinux",
    "Knoppix",
    "ZorinOS",
    "elementaryOS",
    "nixOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "kubuntu",
    "popos",
    "deepin",
]
how = "positive"


[assignment.debian-updates-slow-facette-prefer-fast]
facettes = ["prefer-fast"]
choosables = ["debian"]
how = "negative"


[assignment.runs-in-isolation-facette-privacy-isolation-usage]
facettes = ["privacy-isolation-usage"]
choosables = ["qubesos"]
how = "positive"


[assignment.knoppix-adriane-facette-impaired-view-usage]
facettes = ["impaired-view-usage"]
choosables = ["Knoppix"]
how = "positive"


[assignment.has-software-for-blind-facette-impaired-view-usage]
facettes = ["impaired-view-usage"]
choosables = [
    "ubuntu",
    "debian",
    "devuan",
    "arch",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "rocky",
    "rhel",
    "MXLinux",
    "Fedora",
    "Gentoo",
    "CruxLinux",
    "ZorinOS",
    "elementaryOS",
    "qubesos",
    "nixOS",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "void",
    "artix",
    "popos",
]
how = "positive"


[assignment.has-live-mode-facette-live-mode-usage]
facettes = ["live-mode-usage"]
choosables = [
    "ubuntu",
    "devuan",
    "mint",
    "opensuse",
    "solus",
    "manjaro",
    "pclinuxos",
    "Fedora",
    "Knoppix",
    "ZorinOS",
    "elementaryOS",
    "qubesos",
    "Xubuntu",
    "Lubuntu",
    "UbuntuMATE",
    "void",
    "popos",
    "deepin",
]
how = "positive"


[assignment.slow-release-model-facette-prefer-stable]
facettes = ["prefer-stable"]
choosables = ["debian", "rocky"]
how = "neutral"


[assignment.requires-payment-facette-pricing-free]
facettes = ["pricing-free"]
choosables = ["rhel"]
how = "blocking"



[assignment.general-remark-additional-eula-facette-privacy-no-connections-unless-wanted]
facettes = ["privacy-no-connections-unless-wanted"]
choosables = ["deepin"]
how = "neutral"


[assignment.general-remark-additional-eula-facette-okay-when-working]
facettes = ["okay-when-working"]
choosables = ["ubuntu", "deepin"]
how = "neutral"


[behaviour.gaming-usage-0]
subjects = ["gaming-usage"]
objects = ["privacy-usage"]


[behaviour.already-used-0]
subjects = ["already-used"]
objects = ["beginner-usage"]


[behaviour.knowledge-present-0]
subjects = ["knowledge-present"]
objects = ["beginner-usage", "advanced-usage"]


[behaviour.knowledge-present-1]
subjects = ["knowledge-present"]
objects = ["beginner-usage", "advanced-usage"]


[behaviour.software-admin-answer-console-0]
subjects = ["software-admin-answer-console"]
objects = ["beginner-usage", "no-linux-contact"]


[behaviour.software-admin-answer-console-1]
subjects = ["software-admin-answer-console"]
objects = ["beginner-usage", "no-linux-contact"]


[behaviour.privacy-isolation-usage-0]
subjects = ["privacy-isolation-usage"]
objects = ["beginner-usage", "no-linux-contact", "okay-when-working"]

[behaviour.privacy-isolation-usage-1]
subjects = ["privacy-isolation-usage"]
objects = ["beginner-usage", "no-linux-contact", "okay-when-working"]


[behaviour.privacy-isolation-usage-2]
subjects = ["privacy-isolation-usage"]
objects = ["beginner-usage", "no-linux-contact", "okay-when-working"]
